version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: MySQLServer_Container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Venti
    ports:
      - "3310:3306"
    volumes:
      - C:/Users/NeroH/Documents/Projetos/GerenciamentoDeRH/SQL/VentiSQL.sql:/docker-entrypoint-initdb.d/VentiSQL.sql

    networks:
      - app-network

  backend:
    build: .\Venti
    container_name: Venti_App
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    environment:
      MYSQL_HOST: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Venti?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    restart: on-failure
    entrypoint: >
      /bin/sh -c "while ! nc -z mysql 3306; do sleep 3; done;
      java -jar /app/Venti-0.0.1-SNAPSHOT.jar"

networks:
  app-network:
    driver: bridge
